[phases.setup]
nixPkgs = ["nodejs", "nginx"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run build",
    "cp nginx.conf /etc/nginx/conf.d/default.conf",
    "mkdir -p /usr/share/nginx/html",
    "cp -r dist/* /usr/share/nginx/html/",
    "cp -r public/* /usr/share/nginx/html/public/"
]

[start]
cmd = "nginx -g 'daemon off;'"

[build.args]
VITE_NOCODB_API_TOKEN = "${VITE_NOCODB_API_TOKEN}"
VITE_NOCODB_URL = "${VITE_NOCODB_URL}" 